function onScanSuccess(b,a){barCode=a,$("#qrCode").text(barCode.decodedText),$("#orderNum").val(barCode.decodedText),$(".ecwid-search-btn").css("background","#4f8d18")}$("#orderNum").focus();var orderId,qTickets,fStatus,tktArray,barCode,qChecker,html5QrcodeScanner=new Html5QrcodeScanner("qr-reader",{fps:10,qrbox:{width:220,height:220},rememberLastUsedCamera:!0,supportedScanTypes:[Html5QrcodeScanType.SCAN_TYPE_CAMERA]});function searchTicketOrders(){if($("#orderNum").val().length>5){var a=$("#orderNum").val();$("#orderNum").val(a.slice(-5))}$(".ecwid-search-btn").css("background","#8d1d18");var b="https://app.ecwid.com/api/v3/"+storeId+"/orders?ids="+(orderId=$("#orderNum").val().toUpperCase())+"&token="+key;$.ajax({async:!0,crossDomain:!0,url:b,method:"GET",headers:{Accept:"application/json"}}).done(function(a){if(0==a.count)console.log("NO ITEMS FOUND"),$("#firstName").text("Run"),$("#lastName").text("Search"),$("#email").text("Pending..."),$("#fStatus").text("Pending Search"),$("#qrCode").text("#####"),$("#tickets").text("#"),$("#list-container").empty();else if(a.count>0){$("#firstName").text(a.items["0"].shippingPerson.firstName),$("#lastName").text(a.items["0"].shippingPerson.lastName),$("#email").text(a.items["0"].email);var f=a.items["0"].privateAdminNotes;$("#tickets").text(a.items["0"].items.length),$("#qrCode").text(orderId),qTickets=a.items["0"].items.length,fStatus=a.items["0"].fulfillmentStatus;var b="";if(void 0===f){for(n=0;n<a.items["0"].items.length;n++)b+="0&";b=b.split("&")}else if("&"===f.slice(-1))b=f.split("&");else{for(n=0;n<a.items["0"].items.length;n++)b+="0&";b=b.split("&")}var g=a.items["0"].fulfillmentStatus;"AWAITING_PROCESSING"==g?$("#fStatus").text("Some or none of the tickets have been admitted."):"DELIVERED"==g?$("#fStatus").text("ALL of the tickets have been admitted."):$("#fStatus").text(a.items["0"].fulfillmentStatus);var h="",i="";for(let c=0;c<a.items["0"].items.length;c++){var j=b[c],m=a.items["0"].items[c].name,d=a.items["0"].items[c].quantity;h+=""+d+"&";var k="",l="";j==d&&(l+=" finished",$('div:contains("'+orderId+'")').parent("#party-div").addClass("checked"));for(let e=0;e<=d;e++)k+=`
                                                    <option value="${e}">${e}</option> 
                                    `;i+=`
                                <div class="list-item${l}">
                                    <div class="list-item-title">${m}</div>
                                    <div class="list-item-status">${j} of ${d} tickets admitted</div>
                                    <div class="list-admissions-change-div">
                                    <div class="list-admissions-text">Admitted</div>
                                    <div class="admissions-select w-embed">
                                        <select name="currentQuant" id="quant-${c}" style="padding-left: 10px; padding-right: 10px; width: 50px; height: 36px;">
                                            ${k}
                                        </select>
                                    </div>
                                    <div class="list-admissions-text">Out Of</div><div class="list-total-admissions">${d}</div><div class="list-admissions-text">Tickets</div></div>
                                </div>    
                                `}for(q=0,qChecker=h,document.querySelector(".list-container").innerHTML=i;q<a.items["0"].items.length;q++){var n="#quant-"+q,o=b[q].toString();$(n).val(o).change()}}else console.log("Did not run search")}),$("#orderNum").focus()}function editOrders(){var a="";for(let b=0;b<qTickets;b++)a+=($("#quant-"+b+" option:selected").text().toString()+"&").toString();fStatus=qChecker===a?"DELIVERED":"AWAITING_PROCESSING";var c={async:!0,crossDomain:!0,url:"https://app.ecwid.com/api/v3/"+storeId+"/orders/"+orderId+"?token="+key,method:"PUT",headers:{Accept:"application/json","Content-Type":"application/json"},processData:!0,data:"{privateAdminNotes: "+a+", fulfillmentStatus: "+fStatus+"}"};$.ajax(c).done(function(a){console.log(a),searchTicketOrders()}),$("#orderNum").focus()}html5QrcodeScanner.render(onScanSuccess),$(document).ready(function(){"sItem"in localStorage?($("#orderNum").val(localStorage.getItem("sItem")),searchTicketOrders()):localStorage.removeItem("sItem"),localStorage.removeItem("sItem")}),$("#firstName").text("Run"),$("#lastName").text("Search"),$("#email").text("Pending..."),$("#fStatus").text("Pending Search"),$("#qrCode").text("#####"),$("#tickets").text("#"),$("#list-container").empty(),$("#search").click(function(){searchTicketOrders()}),$("#orderNum").keyup(function(a){13===a.keyCode&&$("#search").click()}),$("#edit").click(function(){editOrders()})
